-- Generated SQL DDL from XSD Schema

CREATE TABLE TNFe (
    id SERIAL NOT NULL PRIMARY KEY,
    refNFe CHAR(44) NOT NULL,
    refNFeSig CHAR(44) NOT NULL,
    refCTe CHAR(44) NOT NULL
);

CREATE TABLE infNFe (
    id SERIAL NOT NULL PRIMARY KEY,
    tnfe_id INTEGER NOT NULL,
    retirada VARCHAR(255),
    entrega VARCHAR(255),
    infRespTec VARCHAR(255),
    refNFe CHAR(44) NOT NULL,
    refNFeSig CHAR(44) NOT NULL,
    refCTe CHAR(44) NOT NULL
);

CREATE TABLE ide (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL,
    cUF CHAR(2) NOT NULL,
    cNF VARCHAR(8) NOT NULL,
    natOp VARCHAR(60) NOT NULL,
    mod CHAR(2) NOT NULL,
    serie INTEGER NOT NULL,
    nNF INTEGER NOT NULL,
    dhEmi TIMESTAMP NOT NULL,
    dhSaiEnt TIMESTAMP,
    tpNF VARCHAR NOT NULL,
    idDest VARCHAR NOT NULL,
    cMunFG CHAR(7) NOT NULL,
    tpImp VARCHAR NOT NULL,
    tpEmis VARCHAR NOT NULL,
    cDV VARCHAR(1) NOT NULL,
    tpAmb CHAR(1) NOT NULL,
    finNFe VARCHAR(255) NOT NULL,
    indFinal VARCHAR NOT NULL,
    indPres VARCHAR NOT NULL,
    indIntermed VARCHAR,
    procEmi VARCHAR(255) NOT NULL,
    verProc VARCHAR(20) NOT NULL,
    refNFe CHAR(44) NOT NULL,
    refNFeSig CHAR(44) NOT NULL,
    refCTe CHAR(44) NOT NULL
);

CREATE TABLE NFref (
    id SERIAL NOT NULL PRIMARY KEY,
    ide_id INTEGER NOT NULL,
    cUF CHAR(2) NOT NULL,
    AAMM VARCHAR(2) NOT NULL,
    CNPJ CHAR(14) NOT NULL,
    mod VARCHAR NOT NULL,
    serie INTEGER NOT NULL,
    nNF INTEGER NOT NULL,
    refNFe CHAR(44) NOT NULL,
    refNFeSig CHAR(44) NOT NULL,
    refCTe CHAR(44) NOT NULL
);

CREATE TABLE refNF (
    id SERIAL NOT NULL PRIMARY KEY,
    tnfe_id INTEGER NOT NULL,
    cUF CHAR(2) NOT NULL,
    AAMM VARCHAR(2) NOT NULL,
    CNPJ CHAR(14) NOT NULL,
    mod VARCHAR NOT NULL,
    serie INTEGER NOT NULL,
    nNF INTEGER NOT NULL
);

CREATE TABLE refNFP (
    id SERIAL NOT NULL PRIMARY KEY,
    tnfe_id INTEGER NOT NULL,
    cUF CHAR(2) NOT NULL,
    AAMM VARCHAR(2) NOT NULL,
    IE VARCHAR(14) NOT NULL,
    mod VARCHAR NOT NULL,
    serie INTEGER NOT NULL,
    nNF INTEGER NOT NULL,
    CNPJ CHAR(14) NOT NULL,
    CPF CHAR(11) NOT NULL
);

CREATE TABLE refECF (
    id SERIAL NOT NULL PRIMARY KEY,
    tnfe_id INTEGER NOT NULL,
    mod VARCHAR NOT NULL,
    nECF VARCHAR NOT NULL,
    nCOO VARCHAR NOT NULL
);

CREATE TABLE emit (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL,
    xNome VARCHAR(60) NOT NULL,
    xFant VARCHAR(60),
    enderEmit VARCHAR(255) NOT NULL,
    IE VARCHAR(14) NOT NULL,
    IEST VARCHAR(14),
    CRT VARCHAR NOT NULL,
    CNPJ CHAR(14) NOT NULL,
    CPF CHAR(11) NOT NULL
);

CREATE TABLE avulsa (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL,
    CNPJ CHAR(14) NOT NULL,
    xOrgao VARCHAR(60) NOT NULL,
    matr VARCHAR(60) NOT NULL,
    xAgente VARCHAR(60) NOT NULL,
    fone VARCHAR,
    UF CHAR(2) NOT NULL,
    nDAR VARCHAR(60),
    dEmi DATE,
    vDAR NUMERIC(15,2),
    repEmi VARCHAR(60) NOT NULL,
    dPag DATE
);

CREATE TABLE dest (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL,
    xNome VARCHAR(60),
    enderDest VARCHAR(255),
    indIEDest VARCHAR NOT NULL,
    IE VARCHAR(255),
    ISUF VARCHAR,
    IM VARCHAR(15),
    email VARCHAR(60),
    CNPJ CHAR(14) NOT NULL,
    CPF CHAR(11) NOT NULL,
    idEstrangeiro VARCHAR NOT NULL
);

CREATE TABLE autXML (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL,
    CNPJ CHAR(14) NOT NULL,
    CPF CHAR(11) NOT NULL
);

CREATE TABLE det (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL,
    infAdProd VARCHAR(500),
    nRECOPI VARCHAR(20) NOT NULL
);

CREATE TABLE prod (
    id SERIAL NOT NULL PRIMARY KEY,
    det_id INTEGER NOT NULL,
    cProd VARCHAR(60) NOT NULL,
    cEAN VARCHAR NOT NULL,
    cBarra VARCHAR(30),
    xProd VARCHAR(120) NOT NULL,
    NCM VARCHAR(2) NOT NULL,
    cBenef VARCHAR(8),
    EXTIPI VARCHAR,
    CFOP VARCHAR(1) NOT NULL,
    uCom VARCHAR(6) NOT NULL,
    qCom NUMERIC(15,4) NOT NULL,
    vUnCom NUMERIC(21,10) NOT NULL,
    vProd NUMERIC(15,2) NOT NULL,
    cEANTrib VARCHAR NOT NULL,
    cBarraTrib VARCHAR(30),
    uTrib VARCHAR(6) NOT NULL,
    qTrib NUMERIC(15,4) NOT NULL,
    vUnTrib NUMERIC(21,10) NOT NULL,
    vFrete NUMERIC(15,2),
    vSeg NUMERIC(15,2),
    vDesc NUMERIC(15,2),
    vOutro NUMERIC(15,2),
    indTot VARCHAR NOT NULL,
    xPed VARCHAR(15),
    nItemPed VARCHAR,
    nFCI UUID,
    nRECOPI VARCHAR(20) NOT NULL
);

CREATE TABLE NVE (
    id SERIAL NOT NULL PRIMARY KEY,
    prod_id INTEGER NOT NULL
);

CREATE TABLE DI (
    id SERIAL NOT NULL PRIMARY KEY,
    prod_id INTEGER NOT NULL,
    nDI VARCHAR(15) NOT NULL,
    dDI DATE NOT NULL,
    xLocDesemb VARCHAR(60) NOT NULL,
    UFDesemb CHAR(2) NOT NULL,
    dDesemb DATE NOT NULL,
    tpViaTransp VARCHAR NOT NULL,
    vAFRMM NUMERIC(15,2),
    tpIntermedio VARCHAR NOT NULL,
    CNPJ CHAR(14),
    UFTerceiro CHAR(2),
    cExportador VARCHAR(60) NOT NULL
);

CREATE TABLE adi (
    id SERIAL NOT NULL PRIMARY KEY,
    di_id INTEGER NOT NULL,
    nAdicao VARCHAR(1),
    nSeqAdic VARCHAR(1) NOT NULL,
    cFabricante VARCHAR(60) NOT NULL,
    vDescDI NUMERIC(15,2),
    nDraw VARCHAR(20)
);

CREATE TABLE detExport (
    id SERIAL NOT NULL PRIMARY KEY,
    prod_id INTEGER NOT NULL,
    nDraw VARCHAR(20)
);

CREATE TABLE exportInd (
    id SERIAL NOT NULL PRIMARY KEY,
    detexport_id INTEGER NOT NULL,
    nRE VARCHAR NOT NULL,
    chNFe CHAR(44) NOT NULL,
    qExport NUMERIC(15,4) NOT NULL
);

CREATE TABLE rastro (
    id SERIAL NOT NULL PRIMARY KEY,
    prod_id INTEGER NOT NULL,
    nLote VARCHAR(20) NOT NULL,
    qLote NUMERIC(11,3) NOT NULL,
    dFab DATE NOT NULL,
    dVal DATE NOT NULL,
    cAgreg VARCHAR(20)
);

CREATE TABLE infProdNFF (
    id SERIAL NOT NULL PRIMARY KEY,
    prod_id INTEGER NOT NULL,
    cProdFisco VARCHAR NOT NULL,
    cOperNFF VARCHAR NOT NULL
);

CREATE TABLE infProdEmb (
    id SERIAL NOT NULL PRIMARY KEY,
    prod_id INTEGER NOT NULL,
    xEmb VARCHAR(8) NOT NULL,
    qVolEmb NUMERIC(11,3) NOT NULL,
    uEmb VARCHAR(8) NOT NULL
);

CREATE TABLE veicProd (
    id SERIAL NOT NULL PRIMARY KEY,
    det_id INTEGER NOT NULL,
    tpOp VARCHAR NOT NULL,
    chassi VARCHAR NOT NULL,
    cCor VARCHAR(4) NOT NULL,
    xCor VARCHAR(40) NOT NULL,
    pot VARCHAR(4) NOT NULL,
    cilin VARCHAR(4) NOT NULL,
    pesoL VARCHAR(9) NOT NULL,
    pesoB VARCHAR(9) NOT NULL,
    nSerie VARCHAR(9) NOT NULL,
    tpComb VARCHAR(2) NOT NULL,
    nMotor VARCHAR(21) NOT NULL,
    CMT VARCHAR(9) NOT NULL,
    dist VARCHAR(4) NOT NULL,
    anoMod VARCHAR(4) NOT NULL,
    anoFab VARCHAR(4) NOT NULL,
    tpPint VARCHAR NOT NULL,
    tpVeic VARCHAR NOT NULL,
    espVeic VARCHAR(1) NOT NULL,
    VIN VARCHAR NOT NULL,
    condVeic VARCHAR NOT NULL,
    cMod VARCHAR NOT NULL,
    cCorDENATRAN VARCHAR(2) NOT NULL,
    lota VARCHAR(3) NOT NULL,
    tpRest VARCHAR NOT NULL
);

CREATE TABLE med (
    id SERIAL NOT NULL PRIMARY KEY,
    det_id INTEGER NOT NULL,
    cProdANVISA VARCHAR(11) NOT NULL,
    xMotivoIsencao VARCHAR(255),
    vPMC NUMERIC(15,2) NOT NULL
);

CREATE TABLE arma (
    id SERIAL NOT NULL PRIMARY KEY,
    det_id INTEGER NOT NULL,
    tpArma VARCHAR NOT NULL,
    nSerie VARCHAR(15) NOT NULL,
    nCano VARCHAR(15) NOT NULL,
    descr VARCHAR(256) NOT NULL
);

CREATE TABLE comb (
    id SERIAL NOT NULL PRIMARY KEY,
    det_id INTEGER NOT NULL,
    cProdANP VARCHAR(9) NOT NULL,
    descANP VARCHAR(95) NOT NULL,
    pGLP NUMERIC(5,4),
    pGNn NUMERIC(5,4),
    pGNi NUMERIC(5,4),
    vPart NUMERIC(15,2),
    CODIF VARCHAR,
    qTemp NUMERIC(16,4),
    UFCons CHAR(2) NOT NULL,
    pBio NUMERIC(15,2)
);

CREATE TABLE CIDE (
    id SERIAL NOT NULL PRIMARY KEY,
    comb_id INTEGER NOT NULL,
    qBCProd NUMERIC(16,4) NOT NULL,
    vAliqProd NUMERIC(15,4) NOT NULL,
    vCIDE NUMERIC(15,2) NOT NULL
);

CREATE TABLE encerrante (
    id SERIAL NOT NULL PRIMARY KEY,
    comb_id INTEGER NOT NULL,
    nBico VARCHAR NOT NULL,
    nBomba VARCHAR,
    nTanque VARCHAR NOT NULL,
    vEncIni NUMERIC(15,3) NOT NULL,
    vEncFin NUMERIC(15,3) NOT NULL
);

CREATE TABLE origComb (
    id SERIAL NOT NULL PRIMARY KEY,
    comb_id INTEGER NOT NULL,
    indImport VARCHAR NOT NULL,
    cUFOrig CHAR(2) NOT NULL,
    pOrig NUMERIC(15,2) NOT NULL
);

CREATE TABLE imposto (
    id SERIAL NOT NULL PRIMARY KEY,
    det_id INTEGER NOT NULL,
    vTotTrib NUMERIC(15,2)
);

CREATE TABLE PIS (
    id SERIAL NOT NULL PRIMARY KEY,
    imposto_id INTEGER NOT NULL,
    CST VARCHAR NOT NULL,
    vBC NUMERIC(15,2) NOT NULL,
    pPIS NUMERIC(5,4) NOT NULL,
    vPIS NUMERIC(15,2) NOT NULL
);

CREATE TABLE PISAliq (
    id SERIAL NOT NULL PRIMARY KEY,
    pis_id INTEGER NOT NULL,
    CST VARCHAR NOT NULL,
    vBC NUMERIC(15,2) NOT NULL,
    pPIS NUMERIC(5,4) NOT NULL,
    vPIS NUMERIC(15,2) NOT NULL
);

CREATE TABLE PISQtde (
    id SERIAL NOT NULL PRIMARY KEY,
    pis_id INTEGER NOT NULL,
    CST VARCHAR NOT NULL,
    qBCProd NUMERIC(16,4) NOT NULL,
    vAliqProd NUMERIC(15,4) NOT NULL,
    vPIS NUMERIC(15,2) NOT NULL
);

CREATE TABLE PISNT (
    id SERIAL NOT NULL PRIMARY KEY,
    pis_id INTEGER NOT NULL,
    CST VARCHAR NOT NULL
);

CREATE TABLE PISOutr (
    id SERIAL NOT NULL PRIMARY KEY,
    pis_id INTEGER NOT NULL,
    CST VARCHAR NOT NULL,
    vPIS NUMERIC(15,2) NOT NULL
);

CREATE TABLE PISST (
    id SERIAL NOT NULL PRIMARY KEY,
    imposto_id INTEGER NOT NULL,
    vPIS NUMERIC(15,2) NOT NULL,
    indSomaPISST VARCHAR
);

CREATE TABLE COFINS (
    id SERIAL NOT NULL PRIMARY KEY,
    imposto_id INTEGER NOT NULL,
    CST VARCHAR NOT NULL,
    vBC NUMERIC(15,2) NOT NULL,
    pCOFINS NUMERIC(5,4) NOT NULL,
    vCOFINS NUMERIC(15,2) NOT NULL
);

CREATE TABLE COFINSAliq (
    id SERIAL NOT NULL PRIMARY KEY,
    cofins_id INTEGER NOT NULL,
    CST VARCHAR NOT NULL,
    vBC NUMERIC(15,2) NOT NULL,
    pCOFINS NUMERIC(5,4) NOT NULL,
    vCOFINS NUMERIC(15,2) NOT NULL
);

CREATE TABLE COFINSQtde (
    id SERIAL NOT NULL PRIMARY KEY,
    cofins_id INTEGER NOT NULL,
    CST VARCHAR NOT NULL,
    qBCProd NUMERIC(16,4) NOT NULL,
    vAliqProd NUMERIC(15,4) NOT NULL,
    vCOFINS NUMERIC(15,2) NOT NULL
);

CREATE TABLE COFINSNT (
    id SERIAL NOT NULL PRIMARY KEY,
    cofins_id INTEGER NOT NULL,
    CST VARCHAR NOT NULL
);

CREATE TABLE COFINSOutr (
    id SERIAL NOT NULL PRIMARY KEY,
    cofins_id INTEGER NOT NULL,
    CST VARCHAR NOT NULL,
    vCOFINS NUMERIC(15,2) NOT NULL
);

CREATE TABLE COFINSST (
    id SERIAL NOT NULL PRIMARY KEY,
    imposto_id INTEGER NOT NULL,
    vCOFINS NUMERIC(15,2) NOT NULL,
    indSomaCOFINSST VARCHAR
);

CREATE TABLE ICMSUFDest (
    id SERIAL NOT NULL PRIMARY KEY,
    imposto_id INTEGER NOT NULL,
    vBCUFDest NUMERIC(15,2) NOT NULL,
    vBCFCPUFDest NUMERIC(15,2),
    pFCPUFDest NUMERIC(5,4),
    pICMSUFDest NUMERIC(5,4) NOT NULL,
    pICMSInter VARCHAR NOT NULL,
    pICMSInterPart NUMERIC(5,4) NOT NULL,
    vFCPUFDest NUMERIC(15,2),
    vICMSUFDest NUMERIC(15,2) NOT NULL,
    vICMSUFRemet NUMERIC(15,2) NOT NULL
);

CREATE TABLE impostoDevol (
    id SERIAL NOT NULL PRIMARY KEY,
    det_id INTEGER NOT NULL,
    pDevol NUMERIC(5,2) NOT NULL
);

CREATE TABLE IPI (
    id SERIAL NOT NULL PRIMARY KEY,
    impostodevol_id INTEGER NOT NULL,
    vIPIDevol NUMERIC(15,2) NOT NULL
);

CREATE TABLE obsItem (
    id SERIAL NOT NULL PRIMARY KEY,
    det_id INTEGER NOT NULL
);

CREATE TABLE obsCont (
    id SERIAL NOT NULL PRIMARY KEY,
    infadic_id INTEGER NOT NULL,
    xTexto VARCHAR(60) NOT NULL
);

CREATE TABLE obsFisco (
    id SERIAL NOT NULL PRIMARY KEY,
    infadic_id INTEGER NOT NULL,
    xTexto VARCHAR(60) NOT NULL
);

CREATE TABLE total (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL
);

CREATE TABLE ICMSTot (
    id SERIAL NOT NULL PRIMARY KEY,
    total_id INTEGER NOT NULL,
    vBC NUMERIC(15,2) NOT NULL,
    vICMS NUMERIC(15,2) NOT NULL,
    vICMSDeson NUMERIC(15,2) NOT NULL,
    vFCPUFDest NUMERIC(15,2),
    vICMSUFDest NUMERIC(15,2),
    vICMSUFRemet NUMERIC(15,2),
    vFCP NUMERIC(15,2) NOT NULL,
    vBCST NUMERIC(15,2) NOT NULL,
    vST NUMERIC(15,2) NOT NULL,
    vFCPST NUMERIC(15,2) NOT NULL,
    vFCPSTRet NUMERIC(15,2) NOT NULL,
    qBCMono NUMERIC(15,2),
    vICMSMono NUMERIC(15,2),
    qBCMonoReten NUMERIC(15,2),
    vICMSMonoReten NUMERIC(15,2),
    qBCMonoRet NUMERIC(15,2),
    vICMSMonoRet NUMERIC(15,2),
    vProd NUMERIC(15,2) NOT NULL,
    vFrete NUMERIC(15,2) NOT NULL,
    vSeg NUMERIC(15,2) NOT NULL,
    vDesc NUMERIC(15,2) NOT NULL,
    vII NUMERIC(15,2) NOT NULL,
    vIPI NUMERIC(15,2) NOT NULL,
    vIPIDevol NUMERIC(15,2) NOT NULL,
    vPIS NUMERIC(15,2) NOT NULL,
    vCOFINS NUMERIC(15,2) NOT NULL,
    vOutro NUMERIC(15,2) NOT NULL,
    vNF NUMERIC(15,2) NOT NULL,
    vTotTrib NUMERIC(15,2)
);

CREATE TABLE ISSQNtot (
    id SERIAL NOT NULL PRIMARY KEY,
    total_id INTEGER NOT NULL,
    vServ NUMERIC(15,2),
    vBC NUMERIC(15,2),
    vISS NUMERIC(15,2),
    vPIS NUMERIC(15,2),
    vCOFINS NUMERIC(15,2),
    dCompet DATE NOT NULL,
    vDeducao NUMERIC(15,2),
    vOutro NUMERIC(15,2),
    vDescIncond NUMERIC(15,2),
    vDescCond NUMERIC(15,2),
    vISSRet NUMERIC(15,2),
    cRegTrib VARCHAR
);

CREATE TABLE retTrib (
    id SERIAL NOT NULL PRIMARY KEY,
    total_id INTEGER NOT NULL,
    vRetPIS NUMERIC(15,2),
    vRetCOFINS NUMERIC(15,2),
    vRetCSLL NUMERIC(15,2),
    vBCIRRF NUMERIC(15,2),
    vIRRF NUMERIC(15,2),
    vBCRetPrev NUMERIC(15,2),
    vRetPrev NUMERIC(15,2)
);

CREATE TABLE transp (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL,
    modFrete VARCHAR NOT NULL,
    CNPJ CHAR(14) NOT NULL,
    CPF CHAR(11) NOT NULL
);

CREATE TABLE transporta (
    id SERIAL NOT NULL PRIMARY KEY,
    transp_id INTEGER NOT NULL,
    xNome VARCHAR(60),
    IE VARCHAR(14),
    xEnder VARCHAR(60),
    xMun VARCHAR(60),
    UF CHAR(2),
    CNPJ CHAR(14) NOT NULL,
    CPF CHAR(11) NOT NULL
);

CREATE TABLE retTransp (
    id SERIAL NOT NULL PRIMARY KEY,
    transp_id INTEGER NOT NULL,
    vServ NUMERIC(15,2) NOT NULL,
    vBCRet NUMERIC(15,2) NOT NULL,
    pICMSRet NUMERIC(5,4) NOT NULL,
    vICMSRet NUMERIC(15,2) NOT NULL,
    CFOP VARCHAR(1) NOT NULL,
    cMunFG CHAR(7) NOT NULL
);

CREATE TABLE vol (
    id SERIAL NOT NULL PRIMARY KEY,
    transp_id INTEGER NOT NULL,
    qVol VARCHAR,
    esp VARCHAR(60),
    marca VARCHAR(60),
    nVol VARCHAR(60),
    pesoL NUMERIC(15,3),
    pesoB NUMERIC(15,3)
);

CREATE TABLE lacres (
    id SERIAL NOT NULL PRIMARY KEY,
    vol_id INTEGER NOT NULL,
    nLacre VARCHAR(60) NOT NULL
);

CREATE TABLE cobr (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL
);

CREATE TABLE fat (
    id SERIAL NOT NULL PRIMARY KEY,
    cobr_id INTEGER NOT NULL,
    nFat VARCHAR(60),
    vOrig NUMERIC(15,2),
    vDesc NUMERIC(15,2),
    vLiq NUMERIC(15,2)
);

CREATE TABLE dup (
    id SERIAL NOT NULL PRIMARY KEY,
    cobr_id INTEGER NOT NULL,
    nDup VARCHAR(60),
    dVenc DATE,
    vDup NUMERIC(15,2) NOT NULL
);

CREATE TABLE pag (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL,
    vTroco NUMERIC(15,2)
);

CREATE TABLE detPag (
    id SERIAL NOT NULL PRIMARY KEY,
    pag_id INTEGER NOT NULL,
    indPag VARCHAR,
    tPag VARCHAR(2) NOT NULL,
    xPag VARCHAR(60),
    vPag NUMERIC(15,2) NOT NULL
);

CREATE TABLE card (
    id SERIAL NOT NULL PRIMARY KEY,
    detpag_id INTEGER NOT NULL,
    tpIntegra VARCHAR NOT NULL,
    CNPJ CHAR(14),
    tBand VARCHAR(2),
    cAut VARCHAR(20)
);

CREATE TABLE infIntermed (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL,
    CNPJ CHAR(14) NOT NULL,
    idCadIntTran VARCHAR(60) NOT NULL
);

CREATE TABLE infAdic (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL,
    infAdFisco VARCHAR(2000),
    infCpl VARCHAR(5000)
);

CREATE TABLE procRef (
    id SERIAL NOT NULL PRIMARY KEY,
    infadic_id INTEGER NOT NULL,
    nProc VARCHAR(60) NOT NULL,
    indProc VARCHAR NOT NULL,
    tpAto VARCHAR
);

CREATE TABLE exporta (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL,
    UFSaidaPais CHAR(2) NOT NULL,
    xLocExporta VARCHAR(60) NOT NULL,
    xLocDespacho VARCHAR(60)
);

CREATE TABLE compra (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL,
    xNEmp VARCHAR(22),
    xPed VARCHAR(60),
    xCont VARCHAR(60)
);

CREATE TABLE cana (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL,
    safra VARCHAR(9) NOT NULL,
    ref VARCHAR NOT NULL,
    qTotMes NUMERIC(21,10) NOT NULL,
    qTotAnt NUMERIC(21,10) NOT NULL,
    qTotGer NUMERIC(21,10) NOT NULL,
    vFor NUMERIC(15,2) NOT NULL,
    vTotDed NUMERIC(15,2) NOT NULL,
    vLiqFor NUMERIC(15,2) NOT NULL
);

CREATE TABLE forDia (
    id SERIAL NOT NULL PRIMARY KEY,
    cana_id INTEGER NOT NULL,
    qtde NUMERIC(21,10) NOT NULL
);

CREATE TABLE deduc (
    id SERIAL NOT NULL PRIMARY KEY,
    cana_id INTEGER NOT NULL,
    xDed VARCHAR(60) NOT NULL,
    vDed NUMERIC(15,2) NOT NULL
);

CREATE TABLE infSolicNFF (
    id SERIAL NOT NULL PRIMARY KEY,
    infnfe_id INTEGER NOT NULL,
    xSolic VARCHAR(5000) NOT NULL
);

CREATE TABLE infNFeSupl (
    id SERIAL NOT NULL PRIMARY KEY,
    tnfe_id INTEGER NOT NULL,
    qrCode VARCHAR(600) NOT NULL,
    urlChave VARCHAR(85) NOT NULL
);

CREATE TABLE TProtNFe (
    id SERIAL NOT NULL PRIMARY KEY
);

CREATE TABLE infProt (
    id SERIAL NOT NULL PRIMARY KEY,
    tprotnfe_id INTEGER NOT NULL,
    tpAmb CHAR(1) NOT NULL,
    verAplic VARCHAR(255) NOT NULL,
    chNFe CHAR(44) NOT NULL,
    dhRecbto TIMESTAMP NOT NULL,
    nProt CHAR(15),
    digVal VARCHAR(255),
    cStat CHAR(3) NOT NULL,
    xMotivo VARCHAR(255) NOT NULL
);

CREATE TABLE TEnviNFe (
    id SERIAL NOT NULL PRIMARY KEY,
    idLote VARCHAR(255) NOT NULL,
    indSinc VARCHAR NOT NULL
);

CREATE TABLE NFe (
    id SERIAL NOT NULL PRIMARY KEY,
    tenvinfe_id INTEGER NOT NULL
);

CREATE TABLE TRetEnviNFe (
    id SERIAL NOT NULL PRIMARY KEY,
    tpAmb CHAR(1) NOT NULL,
    verAplic VARCHAR(255) NOT NULL,
    cStat CHAR(3) NOT NULL,
    xMotivo VARCHAR(255) NOT NULL,
    cUF CHAR(2) NOT NULL,
    dhRecbto TIMESTAMP NOT NULL,
    protNFe VARCHAR(255)
);

CREATE TABLE infRec (
    id SERIAL NOT NULL PRIMARY KEY,
    tretenvinfe_id INTEGER NOT NULL,
    nRec CHAR(15) NOT NULL,
    tMed VARCHAR(255) NOT NULL
);

CREATE TABLE TConsReciNFe (
    id SERIAL NOT NULL PRIMARY KEY,
    tpAmb CHAR(1) NOT NULL,
    nRec CHAR(15) NOT NULL
);

CREATE TABLE TRetConsReciNFe (
    id SERIAL NOT NULL PRIMARY KEY,
    tpAmb CHAR(1) NOT NULL,
    verAplic VARCHAR(255) NOT NULL,
    nRec CHAR(15) NOT NULL,
    cStat CHAR(3) NOT NULL,
    xMotivo VARCHAR(255) NOT NULL,
    cUF CHAR(2) NOT NULL,
    dhRecbto TIMESTAMP NOT NULL
);

CREATE TABLE protNFe (
    id SERIAL NOT NULL PRIMARY KEY,
    tretconsrecinfe_id INTEGER NOT NULL
);

CREATE TABLE TNfeProc (
    id SERIAL NOT NULL PRIMARY KEY,
    NFe VARCHAR(255) NOT NULL,
    protNFe VARCHAR(255) NOT NULL
);

CREATE TABLE TEndereco (
    id SERIAL NOT NULL PRIMARY KEY,
    xLgr VARCHAR(60) NOT NULL,
    nro VARCHAR(60) NOT NULL,
    xCpl VARCHAR(60),
    xBairro VARCHAR(60) NOT NULL,
    cMun CHAR(7) NOT NULL,
    xMun VARCHAR(60) NOT NULL,
    UF CHAR(2) NOT NULL,
    CEP VARCHAR(8),
    cPais VARCHAR,
    xPais VARCHAR(60),
    fone VARCHAR
);

CREATE TABLE TEnderEmi (
    id SERIAL NOT NULL PRIMARY KEY,
    xLgr VARCHAR(60) NOT NULL,
    nro VARCHAR(60) NOT NULL,
    xCpl VARCHAR(60),
    xBairro VARCHAR(60) NOT NULL,
    cMun CHAR(7) NOT NULL,
    xMun VARCHAR(60) NOT NULL,
    UF CHAR(2) NOT NULL,
    CEP VARCHAR(8) NOT NULL,
    cPais VARCHAR,
    xPais VARCHAR,
    fone VARCHAR
);

CREATE TABLE TLocal (
    id SERIAL NOT NULL PRIMARY KEY,
    xNome VARCHAR(60),
    xLgr VARCHAR(60) NOT NULL,
    nro VARCHAR(60) NOT NULL,
    xCpl VARCHAR(60),
    xBairro VARCHAR(60) NOT NULL,
    cMun CHAR(7) NOT NULL,
    xMun VARCHAR(60) NOT NULL,
    UF CHAR(2) NOT NULL,
    CEP VARCHAR(8),
    cPais VARCHAR,
    xPais VARCHAR(60),
    fone VARCHAR,
    email VARCHAR(60),
    IE VARCHAR(14),
    CNPJ VARCHAR(255) NOT NULL,
    CPF CHAR(11) NOT NULL
);

CREATE TABLE TInfRespTec (
    id SERIAL NOT NULL PRIMARY KEY,
    CNPJ VARCHAR(255) NOT NULL,
    xContato VARCHAR(60) NOT NULL,
    email VARCHAR(60) NOT NULL,
    fone VARCHAR NOT NULL
);

CREATE TABLE TVeiculo (
    id SERIAL NOT NULL PRIMARY KEY,
    placa VARCHAR(4) NOT NULL,
    UF CHAR(2),
    RNTC VARCHAR(20)
);

CREATE TABLE TIpi (
    id SERIAL NOT NULL PRIMARY KEY,
    CNPJProd CHAR(14),
    cSelo VARCHAR(60),
    qSelo VARCHAR,
    cEnq VARCHAR(3) NOT NULL
);

CREATE TABLE IPITrib (
    id SERIAL NOT NULL PRIMARY KEY,
    tipi_id INTEGER NOT NULL,
    CST VARCHAR NOT NULL,
    vIPI NUMERIC(15,2) NOT NULL
);

CREATE TABLE IPINT (
    id SERIAL NOT NULL PRIMARY KEY,
    tipi_id INTEGER NOT NULL,
    CST VARCHAR NOT NULL
);


-- Foreign Key Constraints
ALTER TABLE infNFe ADD CONSTRAINT fk_infNFe_tnfe_id FOREIGN KEY (tnfe_id) REFERENCES TNFe(id);
ALTER TABLE ide ADD CONSTRAINT fk_ide_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE NFref ADD CONSTRAINT fk_NFref_ide_id FOREIGN KEY (ide_id) REFERENCES ide(id);
ALTER TABLE refNF ADD CONSTRAINT fk_refNF_tnfe_id FOREIGN KEY (tnfe_id) REFERENCES TNFe(id);
ALTER TABLE refNFP ADD CONSTRAINT fk_refNFP_tnfe_id FOREIGN KEY (tnfe_id) REFERENCES TNFe(id);
ALTER TABLE refECF ADD CONSTRAINT fk_refECF_tnfe_id FOREIGN KEY (tnfe_id) REFERENCES TNFe(id);
ALTER TABLE emit ADD CONSTRAINT fk_emit_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE avulsa ADD CONSTRAINT fk_avulsa_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE dest ADD CONSTRAINT fk_dest_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE autXML ADD CONSTRAINT fk_autXML_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE det ADD CONSTRAINT fk_det_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE prod ADD CONSTRAINT fk_prod_det_id FOREIGN KEY (det_id) REFERENCES det(id);
ALTER TABLE NVE ADD CONSTRAINT fk_NVE_prod_id FOREIGN KEY (prod_id) REFERENCES prod(id);
ALTER TABLE DI ADD CONSTRAINT fk_DI_prod_id FOREIGN KEY (prod_id) REFERENCES prod(id);
ALTER TABLE adi ADD CONSTRAINT fk_adi_di_id FOREIGN KEY (di_id) REFERENCES DI(id);
ALTER TABLE detExport ADD CONSTRAINT fk_detExport_prod_id FOREIGN KEY (prod_id) REFERENCES prod(id);
ALTER TABLE exportInd ADD CONSTRAINT fk_exportInd_detexport_id FOREIGN KEY (detexport_id) REFERENCES detExport(id);
ALTER TABLE rastro ADD CONSTRAINT fk_rastro_prod_id FOREIGN KEY (prod_id) REFERENCES prod(id);
ALTER TABLE infProdNFF ADD CONSTRAINT fk_infProdNFF_prod_id FOREIGN KEY (prod_id) REFERENCES prod(id);
ALTER TABLE infProdEmb ADD CONSTRAINT fk_infProdEmb_prod_id FOREIGN KEY (prod_id) REFERENCES prod(id);
ALTER TABLE veicProd ADD CONSTRAINT fk_veicProd_det_id FOREIGN KEY (det_id) REFERENCES det(id);
ALTER TABLE med ADD CONSTRAINT fk_med_det_id FOREIGN KEY (det_id) REFERENCES det(id);
ALTER TABLE arma ADD CONSTRAINT fk_arma_det_id FOREIGN KEY (det_id) REFERENCES det(id);
ALTER TABLE comb ADD CONSTRAINT fk_comb_det_id FOREIGN KEY (det_id) REFERENCES det(id);
ALTER TABLE CIDE ADD CONSTRAINT fk_CIDE_comb_id FOREIGN KEY (comb_id) REFERENCES comb(id);
ALTER TABLE encerrante ADD CONSTRAINT fk_encerrante_comb_id FOREIGN KEY (comb_id) REFERENCES comb(id);
ALTER TABLE origComb ADD CONSTRAINT fk_origComb_comb_id FOREIGN KEY (comb_id) REFERENCES comb(id);
ALTER TABLE imposto ADD CONSTRAINT fk_imposto_det_id FOREIGN KEY (det_id) REFERENCES det(id);
ALTER TABLE PIS ADD CONSTRAINT fk_PIS_imposto_id FOREIGN KEY (imposto_id) REFERENCES imposto(id);
ALTER TABLE PISAliq ADD CONSTRAINT fk_PISAliq_pis_id FOREIGN KEY (pis_id) REFERENCES PIS(id);
ALTER TABLE PISQtde ADD CONSTRAINT fk_PISQtde_pis_id FOREIGN KEY (pis_id) REFERENCES PIS(id);
ALTER TABLE PISNT ADD CONSTRAINT fk_PISNT_pis_id FOREIGN KEY (pis_id) REFERENCES PIS(id);
ALTER TABLE PISOutr ADD CONSTRAINT fk_PISOutr_pis_id FOREIGN KEY (pis_id) REFERENCES PIS(id);
ALTER TABLE PISST ADD CONSTRAINT fk_PISST_imposto_id FOREIGN KEY (imposto_id) REFERENCES imposto(id);
ALTER TABLE COFINS ADD CONSTRAINT fk_COFINS_imposto_id FOREIGN KEY (imposto_id) REFERENCES imposto(id);
ALTER TABLE COFINSAliq ADD CONSTRAINT fk_COFINSAliq_cofins_id FOREIGN KEY (cofins_id) REFERENCES COFINS(id);
ALTER TABLE COFINSQtde ADD CONSTRAINT fk_COFINSQtde_cofins_id FOREIGN KEY (cofins_id) REFERENCES COFINS(id);
ALTER TABLE COFINSNT ADD CONSTRAINT fk_COFINSNT_cofins_id FOREIGN KEY (cofins_id) REFERENCES COFINS(id);
ALTER TABLE COFINSOutr ADD CONSTRAINT fk_COFINSOutr_cofins_id FOREIGN KEY (cofins_id) REFERENCES COFINS(id);
ALTER TABLE COFINSST ADD CONSTRAINT fk_COFINSST_imposto_id FOREIGN KEY (imposto_id) REFERENCES imposto(id);
ALTER TABLE ICMSUFDest ADD CONSTRAINT fk_ICMSUFDest_imposto_id FOREIGN KEY (imposto_id) REFERENCES imposto(id);
ALTER TABLE impostoDevol ADD CONSTRAINT fk_impostoDevol_det_id FOREIGN KEY (det_id) REFERENCES det(id);
ALTER TABLE IPI ADD CONSTRAINT fk_IPI_impostodevol_id FOREIGN KEY (impostodevol_id) REFERENCES impostoDevol(id);
ALTER TABLE obsItem ADD CONSTRAINT fk_obsItem_det_id FOREIGN KEY (det_id) REFERENCES det(id);
ALTER TABLE obsCont ADD CONSTRAINT fk_obsCont_infadic_id FOREIGN KEY (infadic_id) REFERENCES infAdic(id);
ALTER TABLE obsFisco ADD CONSTRAINT fk_obsFisco_infadic_id FOREIGN KEY (infadic_id) REFERENCES infAdic(id);
ALTER TABLE total ADD CONSTRAINT fk_total_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE ICMSTot ADD CONSTRAINT fk_ICMSTot_total_id FOREIGN KEY (total_id) REFERENCES total(id);
ALTER TABLE ISSQNtot ADD CONSTRAINT fk_ISSQNtot_total_id FOREIGN KEY (total_id) REFERENCES total(id);
ALTER TABLE retTrib ADD CONSTRAINT fk_retTrib_total_id FOREIGN KEY (total_id) REFERENCES total(id);
ALTER TABLE transp ADD CONSTRAINT fk_transp_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE transporta ADD CONSTRAINT fk_transporta_transp_id FOREIGN KEY (transp_id) REFERENCES transp(id);
ALTER TABLE retTransp ADD CONSTRAINT fk_retTransp_transp_id FOREIGN KEY (transp_id) REFERENCES transp(id);
ALTER TABLE vol ADD CONSTRAINT fk_vol_transp_id FOREIGN KEY (transp_id) REFERENCES transp(id);
ALTER TABLE lacres ADD CONSTRAINT fk_lacres_vol_id FOREIGN KEY (vol_id) REFERENCES vol(id);
ALTER TABLE cobr ADD CONSTRAINT fk_cobr_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE fat ADD CONSTRAINT fk_fat_cobr_id FOREIGN KEY (cobr_id) REFERENCES cobr(id);
ALTER TABLE dup ADD CONSTRAINT fk_dup_cobr_id FOREIGN KEY (cobr_id) REFERENCES cobr(id);
ALTER TABLE pag ADD CONSTRAINT fk_pag_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE detPag ADD CONSTRAINT fk_detPag_pag_id FOREIGN KEY (pag_id) REFERENCES pag(id);
ALTER TABLE card ADD CONSTRAINT fk_card_detpag_id FOREIGN KEY (detpag_id) REFERENCES detPag(id);
ALTER TABLE infIntermed ADD CONSTRAINT fk_infIntermed_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE infAdic ADD CONSTRAINT fk_infAdic_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE procRef ADD CONSTRAINT fk_procRef_infadic_id FOREIGN KEY (infadic_id) REFERENCES infAdic(id);
ALTER TABLE exporta ADD CONSTRAINT fk_exporta_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE compra ADD CONSTRAINT fk_compra_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE cana ADD CONSTRAINT fk_cana_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE forDia ADD CONSTRAINT fk_forDia_cana_id FOREIGN KEY (cana_id) REFERENCES cana(id);
ALTER TABLE deduc ADD CONSTRAINT fk_deduc_cana_id FOREIGN KEY (cana_id) REFERENCES cana(id);
ALTER TABLE infSolicNFF ADD CONSTRAINT fk_infSolicNFF_infnfe_id FOREIGN KEY (infnfe_id) REFERENCES infNFe(id);
ALTER TABLE infNFeSupl ADD CONSTRAINT fk_infNFeSupl_tnfe_id FOREIGN KEY (tnfe_id) REFERENCES TNFe(id);
ALTER TABLE infProt ADD CONSTRAINT fk_infProt_tprotnfe_id FOREIGN KEY (tprotnfe_id) REFERENCES TProtNFe(id);
ALTER TABLE NFe ADD CONSTRAINT fk_NFe_tenvinfe_id FOREIGN KEY (tenvinfe_id) REFERENCES TEnviNFe(id);
ALTER TABLE infRec ADD CONSTRAINT fk_infRec_tretenvinfe_id FOREIGN KEY (tretenvinfe_id) REFERENCES TRetEnviNFe(id);
ALTER TABLE protNFe ADD CONSTRAINT fk_protNFe_tretconsrecinfe_id FOREIGN KEY (tretconsrecinfe_id) REFERENCES TRetConsReciNFe(id);
ALTER TABLE IPITrib ADD CONSTRAINT fk_IPITrib_tipi_id FOREIGN KEY (tipi_id) REFERENCES TIpi(id);
ALTER TABLE IPINT ADD CONSTRAINT fk_IPINT_tipi_id FOREIGN KEY (tipi_id) REFERENCES TIpi(id);
